export const ORDER_STATUSES: Record<number, string> = {
  0: 'zignorowane',
  1: 'otrzymane',
  2: 'w procesie anulowania',
  10: 'aktywne',
  11: 'wysłane',
  12: 'częściowo wypełnione',
  20: 'częściowo zrealizowane',
  21: 'zrealizowane',
  30: 'częściowo anulowane',
  31: 'anulowane',
  70: 'odrzucone',
  71: 'wygasło',
  72: 'częściowo zrealizowane i wygasły',
  74: 'błąd podczas wysyłania',
  75: 'błąd podczas anulowania'
};

export const SIGNATURE_TYPES: Record<number, string> = {
  0: 'Bez klucza',
  2: 'za pomocą Tokena',
  3: 'SMS jest hasłem',
  4: 'Login/hasło bez podpisu cyfrowego',
  5: 'E-mail',
  6: 'Hasło głosowe',
  7: 'przez token www',
  8: 'EDS',
  9: 'Quik',
  11: 'Przez polecenie w rejestrze zleceń',
  12: 'FREEDOM Netinvestor - EDS',
  13: 'W formie papierowej',
  14: 'klucz API',
  15: 'Wcześniej złożone polecenie',
  16: 'Zapisano za pomocą protokołu FIX',
  17: 'Zweryfikowano za pomocą aplikacji QR',
  18: 'Multitoken',
  19: 'Weryfikacja face liveness'
};

export const API_TRANSACTION_CODES: Record<string, string> = {
  'bank': 'Przelew bankowy',
  'gift_certificate': 'Aktywacja bonu podarunkowego',
  'trade_cancellation': 'Anulowanie transakcji',
  'blockchain': 'Blockchain',
  'block': 'Blokada',
  'block_commission': 'Blokowanie prowizji',
  'partial_maturity': 'Częściowa spłata',
  'partial_maturity_reverted': 'Częściowa spłata',
  'initial_margin': 'Depozyt zabezpieczający',
  'fund_payment': 'Dochód z jednostek funduszu',
  'fund_payment_reverted': 'Dochód z jednostek funduszu',
  'blik': 'Doładowanie konta przez BLIK',
  'sbp': 'Doładowanie konta przez SBP',
  'digital_assets': 'Doładuj swoje konto poprzez Wallet',
  'dividend': 'Dywidendy',
  'dividend_reverted': 'Dywidendy',
  'stock_dividend': 'Dywidendy według papierów wartościowych',
  'stock_dividend_reverted': 'Dywidendy według papierów wartościowych',
  'merger': 'Działania korporacyjne',
  'merger_reverted': 'Działania korporacyjne',
  'tax_agent': 'Honoraria pośrednictwa podatkowego',
  'stock_dividend_compensation': 'Kompensata dywidend papierami wartościowymi',
  'stock_dividend_compensation_reverted': 'Kompensata dywidend papierami wartościowymi',
  'conversion': 'Konwersja',
  'conversion_reverted': 'Konwersja',
  'coupon': 'Kupon',
  'coupon_reverted': 'Kupon',
  'variation_margin': 'Marża wariacyjna',
  'unblock': 'Odblokowanie',
  'unblock_commission': 'Odblokowanie prowizję',
  'rights_distribution': 'Przeniesienie praw',
  'rights_distribution_reverted': 'Przeniesienie praw',
  'agent_reward_for_commissions': 'Płacenie partnerowi za prowizje klienta',
  'payments_to_customer': 'Płatności na rzecz klienta',
  'dvp': 'Płatność DVP',
  'sepa': 'Płatność SEPA',
  'card': 'Płatność kartą',
  'agent_reward_for_net_deposits': 'Płatność na rzecz partnera za przyciągnięte aktywa',
  'agent_trade': 'Płatność w ramach transakcji agencyjnej',
  'kassa': 'Płatność za gotówkę',
  'commission_rebates': 'Rabat prowizyjny',
  'recurrent_subscription': 'Regularne wypłaty z karty',
  'dividend_compensation': 'Rekompensata dywidend',
  'dividend_compensation_reverted': 'Rekompensata dywidend',
  'card_conversion_settlement': 'Różnice kursowe dla transakcji przy użyciu karty',
  'sepa_instant': 'SEPA Instant',
  'swift': 'SWIFT-płatność',
  'spin_off': 'Spin-off',
  'spin_off_reverted': 'Spin-off',
  'split': 'Split',
  'split_reverted': 'Split',
  'debt_coverage': 'Spłata zadłużenia',
  'maturity': 'Termin zapadalności',
  'maturity_reverted': 'Termin zapadalności',
  'icc_commission': 'Transakcja gotówkowa',
  'system': 'Transakcja systemowa',
  'deposit_compensation': 'Wcześniejsze zakończenie lokaty długoterminowej',
  'storn_correction': 'Wykonanie korekty',
  'cashout': 'Wypłata',
  'crypto_withdrawal': 'Wypłata kryptowalut'
};

export const ORDER_TYPES: Record<number, string> = {
  1: 'Między kontami',
  3: 'Tworzenie weksla',
  4: 'Wystawienie weksla',
  5: 'Przelewy: spłata weksla',
  7: 'Cesja weksla',
  8: 'Przelewy: zakup weksla poprzez cesję',
  9: 'Przelewy: według SWIFT',
  12: 'Prośba o pieniądze',
  13: 'P2P',
  17: 'Prośba o wypłatę z depozytu',
  18: 'Z karty innego banku na kartę klienta',
  19: 'Udzielenie dostępu do produktu',
  20: 'Wyświetlenie CVV/CVC',
  21: 'Otwarcie karty dla dzieci',
  22: 'Do innego banku, według numeru telefonu',
  23: 'Wyświetlanie dokumentów produktu',
  24: 'Ustawienia mapy',
  25: 'Alerty dla karty',
  26: 'Według numeru telefonu',
  28: 'Potwierdzenie 3D Secure',
  29: 'Przegląd transakcji zaufanej karty',
  31: 'Odmowa zaufanej przestrzeni',
  32: 'Pożyczka P2P',
  33: 'Aktualizacja produktu',
  34: 'Otwarcie karty maklerskiej w Armenii',
  35: 'Wydanie elektronicznego podpisu cyfrowego',
  36: 'Spłata pożyczki P2P',
  37: 'Przelew za pomocą karty Mastercard',
  357: 'Aktualizacja zdjęcia paszportu',
  364: 'Wyświetlanie kont bankowych w TN',
  365: 'Odzyskiwanie środków weryfikacji',
  366: 'Otwarcie konta w biurze WalletSolutions',
  367: 'Wypłacanie środków do portfela kryptowalutowego',
  368: 'Doładowanie konta aktywami cyfrowymi',
  372: 'System szybkich płatności',
  373: 'Wypłata pieniędzy za pośrednictwem Systemu szybkich płatności',
  374: 'Crypto Card Cifra Markets',
  375: 'Doładowanie konta przez BLIK',
  376: 'Zakończenie odrębnej ewidencji papierów wartościowych',
  377: 'Doładuj konto',
  400: 'Rezerwacja klientów',
  1000: 'Komunikacja i wsparcie',
  1006: 'Limity',
  1007: 'Blokada',
  1008: 'Ponowne wydanie karty',
  1009: 'Ustawienie kodu PIN',
  1013: 'Otwarcie depozytu',
  1014: 'Depozyty: ustawienia',
  1015: 'Wewnątrz banku',
  1016: 'Między kontami',
  1018: 'Do innego banku',
  1021: 'Przelewy: płatności na rzecz organizacji usługowych',
  1027: 'Między kontami',
  1028: 'Automatyczna płatność',
  1030: 'Prośba o doładowanie depozytu'
};

/**
 * Kontrakt komunikacji z silnikiem podatkowym.
 *
 * Powloka Tauri zapisuje request.json wedlug schematu zadania i odczytuje
 * result.json albo error.json wedlug schematu odpowiedzi. Obie strony
 * odrzucaja plik o niezgodnej nazwie schematu.
 */
export const REQUEST_CONTRACT_VERSION = 'investanalyzer.analysis-request.v1';
export const RESULT_CONTRACT_VERSION = 'investanalyzer.analysis-result.v1';

/**
 * Ile czasu silnik ma na jeden przebieg - odpowiednik ENGINE_TIMEOUT_SECONDS
 * w powloce Tauri. Interfejs musi czekac przynajmniej tyle samo: krotszy limit
 * po stronie ekranu konczy sie komunikatem "nadal trwa" przy zadaniu, ktore
 * spokojnie by sie skonczylo.
 */
export const ENGINE_TIMEOUT_MS = 600_000;
